### ISSUE TITLE
CommonJS incompatibility 

### ISSUE THREAD

**Issue by rompemoldes** [sindresorhus/random-word#7]
After updating the `random-word` module from `^2.0.0` to `^3.0.0` on my project and trying to run a file using it, I get this error on my shell:

``` bash
/Users/fooUser/Visual_Studio_Code/txd-load-test/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/fooUser/Visual_Studio_Code/txd-load-test/node_modules/random-word/index.js from /Users/fooUser/Visual_Studio_Code/txd-load-test/source/barFile.ts not supported.
Instead change the require of index.js in /Users/fooUser/Visual_Studio_Code/txd-load-test/source/barFile.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/fooUser/Visual_Studio_Code/txd-load-test/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/fooUser/Visual_Studio_Code/txd-load-test/source/barFile.ts:41:39)
    at m._compile (/Users/fooUser/Visual_Studio_Code/txd-load-test/node_modules/ts-node/dist/index.js:857:29) {
  code: 'ERR_REQUIRE_ESM'
}
```

My `tsconfig.json` looks like this: 

``` json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

I'm using `yarn@4.3.1`

## My temporary solution

I downgraded to `"random-word: "^2.0.0"` again.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
